name: Rust Release Builder

on: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Run tests
      run: cargo test --verbose

    - name: Install cross compiler
      run: cargo install cross

    - name: Build and compress x86_64 binaries with xz
      run: |
        cargo build --release
        xz -T0 -f ${GITHUB_WORKSPACE}/target/release/qrlink
        mv ${GITHUB_WORKSPACE}/target/release/qrlink.xz ${GITHUB_WORKSPACE}/target/release/qrlink.x86_64.xz
 
    - name: Build and compress armv7 binaries with xz
      run: |
        cross build --target armv7-unknown-linux-gnueabihf --release
        xz -T0 -f ${GITHUB_WORKSPACE}/target/armv7-unknown-linux-gnueabihf/release/qrlink
        mv ${GITHUB_WORKSPACE}/target/armv7-unknown-linux-gnueabihf/release/qrlink.xz ${GITHUB_WORKSPACE}/target/armv7-unknown-linux-gnueabihf/release/qrlink.armv7.xz

    - name: Release ARMv7 binary
      uses: JasonEtco/upload-to-release@master
      with:
        args: /github/workspace/target/armv7-unknown-linux-gnueabihf/release/qrlink.armv7.xz application/x-xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release x86-64 binary
      uses: JasonEtco/upload-to-release@master
      with:
        args: /github/workspace/target/release/qrlink.x86_64.xz application/x-xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

